#
# algolia-search.yml
#
# Create a search index for Algolia Search when code is pushed to main.
#

name: Algolia-Search
on:
  push:
    branches:
      - main
jobs:
  wait-for-vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel to deploy
        run: |
          sleep 30s
        shell: bash

  algolia-search:
    runs-on: ubuntu-latest
    needs: [wait-for-vercel-deploy]
    steps:
      - name: "Update Algolia Search Index"
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: ${{ secrets.ALGOLIA_APP_ID}}
          algolia_api_key: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          file: "./algolia-config.json"
