#
# algolia-search.yml
#
# Create a search index for Algolia Search when code is pushed to main.
#

name: Algolia-Search
on:
  push:
    branches:
      - main

jobs:
  wait-for-vercel-deployment:
    runs-on: ubuntu-18.04
    steps:
      - name: Retrieve deployment URL
        run: "echo VERCEL_DEPLOYMENT_URL=docs2-minadocs.vercel.app >> $GITHUB_ENV"
      - uses: UnlyEd/github-action-await-vercel@v1.1.0
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ env.VERCEL_DEPLOYMENT_URL }}
          timeout: 20
  algolia-search:
    runs-on: ubuntu-latest
    needs: [wait-for-vercel-deployment]
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: ${{ secrets.ALGOLIA_APP_ID}}
          algolia_api_key: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          file: "./algolia-config.json"
